databaseChangeLog:
  - include:
      file: 0001_create_table_developers.yaml
      relativeToChangelogFile: true
  - include:
      file: 0002_create_table_achivments.yaml
      relativeToChangelogFile: true
  - include:
      file: 0003_create_table_skills.yaml
      relativeToChangelogFile: true
  - include:
      file: 0004_create_table_companies.yaml
      relativeToChangelogFile: true
  - include:
      file: 0005_create_table_benefits.yaml
      relativeToChangelogFile: true
  - include:
      file: 0006_create_table_projects.yaml
      relativeToChangelogFile: true
  - include:
      file: 0007_create_FK_projects_benefits.yaml
      relativeToChangelogFile: true
  - include:
      file: 0008_create_table_projects_skills.yaml
      relativeToChangelogFile: true
  - include:
      file: 0009_create_table_developers_skills.yaml
      relativeToChangelogFile: true
  - include:
      file: 0010_create_table_developers_achievements.yaml
      relativeToChangelogFile: true
  - include:
      file: 0011_create_table_table_to_matches.yaml
      relativeToChangelogFile: true